base:
  app_name: "data-collection-hub"
  app_port: "8080"
  app_host: "localhost"
  app_version: "1.0.0"
casbin:
  --snip-- # TODO: Add casbin configuration
jwt:
  jwt_secret_key: "SECRET"
  jwt_token_expire_in: 3600
  jwt_refresh_token_expire_in: 7200
mongo:
  mongo_uri: "mongodb://localhost:27017"
  mongo_database: "data-collection-hub"
  mongo_connect_timeout_ms: 10000
  mongo_max_pool_size: 10
  mongo_min_pool_size: 1
  mongo_socket_timeout_ms: 10000
redis:
  redis_addr: "localhost:6379"
  redis_client_name: ""
  redis_username: ""
  redis_password: ""
  redis_db: 0
  redis_max_retries: 5
  redis_min_retry_backoff: 8ms
  redis_max_retry_backoff: 512ms
  redis_dial_timeout: 5s
  redis_read_timeout: 3s
  redis_write_timeout: 3s
  redis_pool_size: 10
  redis_pool_timeout: 4s
  redis_min_idle_conns: 0
  redis_max_active_conns: 30m
  redis_conn_max_idle_time: 30m
  redis_conn_max_lifetime: -1
zap:
  zap_level: "info"
  zap_encoding: "console"
  zap_encoder_level: "capital"
  zap_development: true
  zap_disable_caller: false
  zap_disable_stacktrace: false
  zap_output_paths: [ "stdout" ]
  zap_error_output_paths: [ "stderr" ]
fiber:
  prefork: false
  server_header: ""
  body_limit: 4194304
  concurrency: 262144
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 120s
  read_buffer_size: 4096
  write_buffer_size: 4096
  proxy_header: "X-Forwarded-For"
  disable_keepalive: false
  disable_startup_message: false
  reduce_memory_usage: false
  enable_trusted_proxy_check: false
  trusted_proxies: []
  enable_print_routes: true
limiter:
  limiter_max: 100
  limiter_expiration: 10s